update notebooks for 5.0.3 and fix metrics plugin versions
IBM/watson-openscale-samples pull request #176
Opened 2024-11-07 09:35 UTC by pratapkishorevarma

2024-11-07 10:46 UTC, prempiyush requested changes
General comment. 

For all the files changed, I think we should change the copyright year too.

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.5/hive/Watson OpenScale - Monitor models with data in Hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.5.0` to `!pip install "ibm_wos_utils~=4.5.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.5/jdbc/Watson OpenScale - Monitor models with data in DB2.ipynb
Please change this `!pip install ibm_wos_utils>=4.5.0` to `!pip install "ibm_wos_utils~=4.5.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/hive/Watson OpenScale - Monitor models with data in Hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.5.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/hive/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.6.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/hive/samples/Watson OpenScale and Batch - WML - IAE - hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.6.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/jdbc/Watson OpenScale - Monitor models with data in DB2.ipynb
Please change this `!pip install ibm_wos_utils>=4.5.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/jdbc/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.6.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.6/jdbc/samples/Watson OpenScale and Batch - WML - IAE - JDBC.ipynb
Please change this `!pip install ibm_wos_utils>=4.6.0` to `!pip install "ibm_wos_utils~=4.6.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/hive/Watson OpenScale - Monitor models with data in Hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/hive/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/hive/samples/Watson OpenScale and Batch - WML - IAE - hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/jdbc/Watson OpenScale - Monitor models with data in DB2.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/jdbc/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`v

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.7/jdbc/samples/Watson OpenScale and Batch - WML - IAE - JDBC.ipynb
Please change this `!pip install ibm_wos_utils>=4.7.0` to `!pip install "ibm_wos_utils~=4.7.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/hive/Watson OpenScale - Onboard models for monitoring using Configuration Package.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/hive/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/hive/samples/Watson OpenScale and Batch - WML - IAE - hive.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/jdbc/Watson OpenScale - Onboard models for monitoring using Configuration Package.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/jdbc/Watson OpenScale - Onboard models for monitoring using training data table and a sample csv.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on Cloud Pak for Data/Batch Support/4.8/jdbc/samples/Watson OpenScale and Batch - WML - IAE - JDBC.ipynb
Please change this `!pip install ibm_wos_utils>=4.8.0` to `!pip install "ibm_wos_utils~=4.8.0"`

2024-11-07 10:46 UTC, prempiyush commented on IBM Cloud/AWS Sagemaker/notebooks/Credit  model with SageMaker linear-learner .ipynb
If sagemaker is not being used, perhaps better to delete the installation line.

2024-11-07 10:46 UTC, prempiyush commented on WatsonX.Governance/Cloud/GenAI/samples/Detached Prompt Evaluation HF FLAN model.ipynb
No command to install ibm_watsonx_ai?

2024-11-07 10:46 UTC, prempiyush commented on WatsonX.Governance/Cloud/GenAI/samples/Detached Prompt Evaluation RAG task type.ipynb
No command to install ibm_watsonx_ai?

2024-11-07 12:27 UTC, ravichamarthy commented
When you changes all the files with the metrics plugin version, did you also run all the notebooks to make sure they are working fine?

2024-11-07 14:03 UTC, sokollip approved these changes

2024-11-07 14:53 UTC, pratapkishorevarma commented
> General comment.
> 
> For all the files changed, I think we should change the copyright year too.

Only few notebooks have copyright footer. If we want to add them, need to handle as part of a new task.

2024-11-08 04:54 UTC, prempiyush approved these changes

2024-11-08 05:53 UTC, merged

2024-11-26 16:54 UTC, csgorham commented
keep getting this error "numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject"  tried ```!pip install  pybind11>=2.12
!pip install numpy==1.26.4'''